version: "3.7"

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  flask_service:
    restart: always
    image: flask
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/flask
    environment:
        - FLASK_DEBUG=1
